# Use node for the first stage
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# In development, we'll use npm run dev
# This Dockerfile is shared with the backend for simplicity in dev
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
