apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goalixa-admin-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: goalixa
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/goalixa/admin_panel.git
    targetRevision: staging
    path: helm
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: goalixa-admin-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      name: admin-secrets
      jsonPointers:
        - /data
